In [1]:
import torch
import numpy as np
import os
import pandas as pd

In [12]:
# Get filenames from folder
path = "./brain/"  # multicoil data (from)
filenames = []
for file in os.listdir(path):
    filenames.append(file)
    
val_hist = []
for fname in filenames:
    print(fname)
    q = 1-np.array(torch.load(path+fname))
    print(len(q))
    val_hist.append(q)

Unet_124M_35k_val.pt
9
Unet_124M_70k_val.pt
9
Unet_31M_35k_val.pt
9
Unet_31M_70k_val.pt
5
Unet_8M_35k_val.pt
8
Unet_8M_70k_val.pt
8
ViT_MHSAp10_32M_35k_val.pt
9
ViT_MHSAp10_32M_70k_val.pt
5
ViT_MHSAp10_60M_35k_val.pt
10
ViT_MHSAp10_60M_70k_val.pt
9
ViT_MHSAp10_8M_35k_val.pt
8
ViT_MHSAp10_8M_70k_val.pt
8


In [23]:
from matplotlib import pyplot as plt
val_hist[8]

array([      -inf, 0.81250176, 0.82069345, 0.82293909, 0.82345955,
       0.82414766, 0.82453752, 0.82495272, 0.82510632, 0.82525316])

In [62]:
val_hist[1]

array([      -inf, 0.82440745, 0.82614121, 0.82662158, 0.82694099,
       0.82694306, 0.82692571, 0.82679184, 0.82658413])

In [46]:
val_hist_ = []

In [55]:
val_hist_.append(val_hist[11][:])

In [56]:
val_hist_

[array([0.82254719, 0.82432532, 0.82534031, 0.8257592 , 0.82576407,
        0.82574122, 0.82551889, 0.82527426]),
 array([0.82440745, 0.82614121, 0.82662158, 0.82694099, 0.82694306,
        0.82692571, 0.82679184, 0.82658413]),
 array([0.82052146, 0.82197198, 0.82299277, 0.82332244, 0.82363285,
        0.82379985, 0.82389123, 0.82396089]),
 array([0.8210492 , 0.82321124, 0.82391433, 0.82402646, 0.824442  ,
        0.82456649, 0.82471094, 0.82479626]),
 array([0.82069345, 0.82293909, 0.82345955, 0.82414766, 0.82453752,
        0.82495272, 0.82510632, 0.82525316]),
 array([0.82208091, 0.82467831, 0.82565577, 0.82631242, 0.82674595,
        0.82695177, 0.82722603, 0.82738368]),
 array([0.81111144, 0.81589619, 0.81780464, 0.81889134, 0.81995401,
        0.82055195, 0.82106728, 0.82138767]),
 array([0.81485748, 0.81930406, 0.82058838, 0.8212971 , 0.82169303,
        0.82217326, 0.82252203, 0.82277677])]

In [57]:
val_hist_np = np.stack(val_hist_)

In [58]:
import pandas as pd  
  
# Calling DataFrame constructor  
df = pd.DataFrame()

In [61]:
val_hist_np[:,1]

array([0.82432532, 0.82614121, 0.82197198, 0.82321124, 0.82293909,
       0.82467831, 0.81589619, 0.81930406])

In [59]:
datak = [35, 70, 35, 70, 35, 70, 35, 70,]

In [64]:
models = [
    'U-Net-124M', 
    'U-Net-124M',       
    'U-Net-8M', 
    'U-Net-8M',    
    'ViT-60M/10', 
    'ViT-60M/10', 
    'ViT-8M/10', 
    'ViT-8M/10',     
    ]

In [65]:
data = {'Model':models, 'Data in k': datak, 'Epoch 5': val_hist_np[:,0], 
        'Epoch 10': val_hist_np[:,1], 'Epoch 15': val_hist_np[:,2], 'Epoch 20': val_hist_np[:,3], 
        'Epoch 25': val_hist_np[:,4], 'Epoch 30': val_hist_np[:,5], 'Epoch 35': val_hist_np[:,6], 'Epoch 40': val_hist_np[:,7],
       }
dframe = pd.DataFrame(data)  

In [66]:
print(dframe)

        Model  Data in k   Epoch 5  Epoch 10  Epoch 15  Epoch 20  Epoch 25  \
0  U-Net-124M         35  0.822547  0.824325  0.825340  0.825759  0.825764   
1  U-Net-124M         70  0.824407  0.826141  0.826622  0.826941  0.826943   
2    U-Net-8M         35  0.820521  0.821972  0.822993  0.823322  0.823633   
3    U-Net-8M         70  0.821049  0.823211  0.823914  0.824026  0.824442   
4  ViT-60M/10         35  0.820693  0.822939  0.823460  0.824148  0.824538   
5  ViT-60M/10         70  0.822081  0.824678  0.825656  0.826312  0.826746   
6   ViT-8M/10         35  0.811111  0.815896  0.817805  0.818891  0.819954   
7   ViT-8M/10         70  0.814857  0.819304  0.820588  0.821297  0.821693   

   Epoch 30  Epoch 35  Epoch 40  
0  0.825741  0.825519  0.825274  
1  0.826926  0.826792  0.826584  
2  0.823800  0.823891  0.823961  
3  0.824566  0.824711  0.824796  
4  0.824953  0.825106  0.825253  
5  0.826952  0.827226  0.827384  
6  0.820552  0.821067  0.821388  
7  0.822173  0.822522  0.

In [67]:
dframe.to_excel('./val_hist_brain.xlsx', index = False)

In [108]:
!pip install openpyxl


You should consider upgrading via the 'c:\users\kang\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.
